config/routes.rb
Rails.application.routes.draw do

   root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'home'    => 'static_pages#home_after_login'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
    resources :users do
    member do
      get :following, :followers
    end
  end

    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :entries
    resources :comments
    resources :relationships,       only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    
    @users = User.paginate(page: params[:page])
    @user = User.new
    #@entry  = current_user.entries.build
    #@feed_items = current_user.feed.paginate(page: params[:page])
    
  end

  def help
  end

  def about
  end

  def contact
  end
  def home_after_login


  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>

  <%= render "users/index"%>

<% else %>
      <div class = "signin-from-root">
        <h1>
          Log in
        </h1>
        <%= form_for(:session, url: login_path) do |f| %>
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>        

                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>

                <%= f.label :remember_me, class: "checkbox inline" do %>
                <%= f.check_box :remember_me %>
                <span>Remember me on this computer</span>
                <% end %>

                <%= f.submit "Log in", class: "btn btn-primary" %> <br>

                <%# link_to "Fogot password?", new_password_reset_path %>
          <% end %>
      </div>
      
      <div class="signup-from-root">
        <h1>
          Are you new user?
        </h1>
         Sign up now. It's free, always will be.<br>
        <%= render "users/new" %>
      </div>
<% end %>