config/routes.rb
Rails.application.routes.draw do

   root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'home'    => 'static_pages#home_after_login'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
    resources :users do
    member do
      get :following, :followers
    end
  end

    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :entries
    resources :comments
    resources :relationships,       only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :entries, dependent: :destroy
  has_many :comments, dependent: :destroy
  # User co nhieu quan he following(thuoc loai active_ralationship) voi source cua no la followed_id
  # Luu y la 2 dong dau da dat quan he giua user va ralationship roi!
  has_many :active_relationships, class_name: "Relationship", 
                                   foreign_key: "follower_id", 
                                   dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  

  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  # attr_accessor la 1 phuong thuc, co tac dung la cac hash cua no khong can phai dinh nghia trong CT
  # O duoi, co su dung remember_token, activation_token, reset_token ma truoc do ko can dinh nghia
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
    validates :password, length: { minimum: 6 }, allow_blank: true


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  #Gan cho bien digest gia tri bang voi gia tri digest can xac nhan(password_digest, rememner_diggest hoac reset_digest)
  #Ma hoa chuoi digest nhan dc, kiem tra xem co trung voi gia tri token tuong ung trong session ko
  #Co thi tra lai true, nguoc lai la false
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  # Ham dc goi trong truong hop dang xuat
  # Chuyen gia tri remember_digest ve nil
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  # Tao mot reset_digest(thuc ra la tao 1 token roi gan gia tri cho digest bang voi token) --> luu no vao CSDL
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  # Defines a proto-feed.
  # See "Following users" for the full implementation.
  def feed
        following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Entry.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)

  end
  
 # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
  
  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index  
    @users = User.paginate(page: params[:page])
  end
  def show
    @user = User.find(params[:id])
    #@entry = current_user.entries.build(entry_params)
   # id = @user.id
    @entries = @user.entries.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end
  def update

    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_url(@user)
  end
  def create
    @user = User.new(user_params)
    #@user.activated = true;
    if @user.save
      #@user.send_activation_email
      #UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Thank you, your sign-up request was successful. Please, login now"

      redirect_to root_url
    else
      #render 'new'
      render 'static_pages/home'
      #redirect_to root_url
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  def  destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url   
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
   # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      #redirect_to(root_url) unless current_user?(@user)
      redirect_to(root_url) unless @user == current_user
    end
# Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { :size => 10 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.
                          build(followed_id: @user.id),
                          remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_index.html.erb
<aside class="col-md-4">
	<% provide(:title, 'All users') %>
	All users
	<ul class="users">
	      <%= render @users %>
	</ul>
	<%= will_paginate @users%>
</aside>

app/views/users/_new.html.erb
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>

app/views/users/_new_comment.html.erb
<section class="comment_form">
                      <%= form_for(Comment.new, html: { multipart: true }) do |f| %>
                        <%= render 'shared/error_messages', object: f.object %>
                        <div class="field">
                          <%= f.text_field :content, placeholder: "Comment..." %>
                          <%= f.number_field :user_id, :value => @userid, :hidden =>true%>
                          <%= f.number_field :entries_id, :value => @entryid, :hidden =>true %>
                        </div>
                        <%= f.submit "Post", :hidden => true%>
                      <% end %>
                </section>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 10%>
  <%= link_to user.name, user %>
  <% if !current_user.nil? %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
  <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user, size: 10 %>
      <a href="http://gravatar.com/emails">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'index' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<div class="row">
  <aside class="col-md-2">
    <section>
      <h1>
        <%= gravatar_for @user, size: 10 %>
        <%= @user.name %>
      </h1>
    </section>

    <section class="stats">
      <%= render 'shared/stats' %>
    </section>

    <section class="list-entry">
      <%if logged_in? %>
      <%= link_to "Find friends", users_url %><br>
      <%= link_to "Create new entry", new_entry_path %><br>
      <% end %>
      List entries (<%= @user.entries.count %>)

      <% @entries.each do |entry| %>      
        <span class="title">
                  <%= link_to entry.title, entry %>
                  <% if current_user?(entry.user) %>|
                    <%= link_to "Delete", entry, method: :delete,
                                                     data: { confirm: "You sure?" } %>
                  <% end %>
        </span>     
      <% end %>
      <%= will_paginate @entries%>
    </section>

  </aside>


  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.entries.any? %>
      
      <% @entries.each do |entry| %>
        <ol class="entries">
                <%= link_to gravatar_for(entry.user, size: 10), entry.user %>

                <span class="user">
                  <%= link_to entry.user.name, entry.user %>
                </span><br>

                <span class = "title-in-feed">
                  <%= entry.title %><br>
                </span>
                 
                <span class="timestamp">
                  <%= time_ago_in_words(entry.created_at) %> ago.
                  <% if current_user?(entry.user) %>|
                    <%= link_to "Delete", entry, method: :delete,
                                                     data: { confirm: "You sure?" } %>|
                    <%= link_to "Edit", edit_entry_path(entry) %>
                  <% end %>
                </span>
                <span class="content">
                 
                  <%= entry.body %>
                  <%= image_tag entry.picture.url if entry.picture? %>
                </span>
                <br>
             
               <% @comments2 = Comment.where("entries_id = #{entry.id}") %>
               <%if @comments2.length>0 %>
                  <% @comments2.each do |comment| %>
                      <br>
                      <% user = User.find_by(id: comment.user_id) %>
                      <%if !user.nil?%>
                        <span class = "username">                  
                          <%= link_to user.name, entry.user %>:
                        </span>
                      
                      <% end %>
                      <%= comment.content %> <br>
                      <span class="timestamp">
                        <%= time_ago_in_words(comment.created_at) %> ago.
                        <% if !current_user.nil? && comment.user_id == current_user.id%>|
                        <%= link_to "Delete", comment, method: :delete,
                                                           data: { confirm: "You sure?" } %>
                        <% end %>
                      </span>
                  <% end %>
               <% end %>
               <%
                  @userid = current_user.id if logged_in?
                  @entryid = entry.id
               %>
               <%= render 'new_comment' %>              
               <hr class="fancy-line"></hr>
                
        </ol>
    <% end %>
      

      
    <% end %>

  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= gravatar_for @user, size: 10 %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.entries.any? %>
      <h3>Entries (<%= @user.entries.count %>)</h3>
      <ol class="entries">
        <%= render @entries %>
      </ol>
      <%= will_paginate @entries %>
    <% end %>
  </div>
</div>